# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html

services:
    # Doctrine Extension listeners to handle behaviors
    gedmo.listener.tree:
        class: Gedmo\Tree\TreeListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]

    gedmo.listener.translatable:
        class: Gedmo\Translatable\TranslatableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]
            - [ setDefaultLocale, [ %locale% ] ]
            - [ setTranslationFallback, [ false ] ]

    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]

    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]

    gedmo.listener.sortable:
        class: Gedmo\Sortable\SortableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]

    gedmo.listener.loggable:
        class: Gedmo\Loggable\LoggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]

    eshop.upload_listener:
        class:        Eshop\ShopBundle\EventListener\UploadListener
        arguments:    ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_upload, method: onUpload }

    app.locale_listener:
        class: Eshop\ShopBundle\EventListener\LocaleListener
        arguments:    ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }

    fos_user.doctrine_registry:
        alias: doctrine

    app.email_notifier:
        class:        Eshop\ShopBundle\Service\EmailNotifier
        arguments:    ["@swiftmailer.mailer", "@router", "@templating"]

    app.page_utilities:
        class:        Eshop\ShopBundle\Service\PagesUtilities
        arguments:    ["@doctrine.orm.entity_manager"]

    my.sitemap.listener:
        class:        Eshop\ShopBundle\EventListener\SitemapListener
        arguments:    ["@router", "@doctrine.orm.entity_manager"]
        tags:
            - { name: "presta.sitemap.listener" }

    app.form.registration:
        class:        Eshop\UserBundle\Form\Type\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

    app.twig_extension:
        class:        Eshop\ShopBundle\Twig\RawDescriptionExtension
        public:       false
        tags:
            - { name: twig.extension }

    price.twig_extension:
        class:        Eshop\ShopBundle\Twig\PriceExtension
        public:       false
        tags:
            - { name: twig.extension }

    discount.twig_extension:
        class:        Eshop\ShopBundle\Twig\DiscountExtension
        public:       false
        tags:
            - { name: twig.extension }

    enabled.twig_extension:
        class:        Eshop\ShopBundle\Twig\EnabledExtension
        public:       false
        tags:
            - { name: twig.extension }

    my_user_provider:
        class:        Eshop\UserBundle\Security\Core\User\FOSUBUserProvider
        arguments:    ["@fos_user.user_manager", {facebook: facebook_id, google: google_id}]
